name: HQIU SQL Linting Action

on:
  workflow_call:

jobs:
  lint-sql:
    runs-on: ubuntu-latest
    container: dohwahqiu/lint:sql
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Get changed files
        id: get_file_changes
        uses: tj-actions/changed-files@v17.2
        with:
          separator: ","

      - name: Get changed SQL files to lint
        id: get_files_to_lint
        run: |
          # Set the command in the $() brackets as an output to use in later steps
          echo "::set-output name=lintees::$(
          # Issue where grep regular expressions don't work as expected on the
          # Github Actions shell, check ALL
          echo \
          $(echo ${{ steps.get_file_changes.outputs.all_changed_files }} |
          sed 's/,/\",\"/g' | sed 's/^/\"/' | sed 's/$/\"/' |
          tr -s ',' '\n' |
          grep -E '..*[.]sql\"$' |
          tr -s '\n' ' ')
          )"
        shell: bash -l {0}

      - name: Get SQL coding style config
        run: |
          curl https://raw.githubusercontent.com/AUS-DOH-Safety-and-Quality/HQIU-Coding-Styles/main/SQL/.sqlfluff -o .sqlfluff

      - name: Lint and annotate changed SQL files
        id: sqlfluff_json
        if: steps.get_files_to_lint.outputs.lintees != ''
        run: |
          sqlfluff lint --ignore parsing --format github-annotation --annotation-level failure --nofail ${{ steps.get_files_to_lint.outputs.lintees }} > annotations.json
        shell: bash -l {0}

      - name: Annotate
        uses: yuzutech/annotations-action@v0.3.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: "SQLFluff Lint"
          input: "./annotations.json"
